export type DailyQuestion = {
  id: number;
  question: string;
  options: readonly [string, string];
  correctOption: 0 | 1;
};

export const questions: readonly DailyQuestion[] = [
  {
    id: 1,
    question: "Which came first?",
    options: ["Base Mainnet", "Farcaster Frames"],
    correctOption: 0,
  },
  {
    id: 2,
    question: "Base was incubated by which company?",
    options: ["Coinbase", "Optimism"],
    correctOption: 0,
  },
  {
    id: 3,
    question: "Base is built using which Ethereum scaling stack?",
    options: ["OP Stack", "Polygon CDK"],
    correctOption: 0,
  },
  {
    id: 4,
    question: "Base settles its transactions to which network?",
    options: ["Ethereum", "Solana"],
    correctOption: 0,
  },
  {
    id: 5,
    question: "What type of Ethereum network is Base?",
    options: ["Layer 2", "Layer 1"],
    correctOption: 0,
  },
  {
    id: 6,
    question: "Which organization develops the OP Stack?",
    options: ["Optimism", "Arbitrum"],
    correctOption: 0,
  },
  {
    id: 7,
    question: "Does Base have a native network token?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 8,
    question: "Which asset is used to pay gas fees on Base?",
    options: ["ETH", "BASE"],
    correctOption: 0,
  },
  {
    id: 9,
    question: "Base is compatible with which virtual machine?",
    options: ["EVM", "SVM"],
    correctOption: 0,
  },
  {
    id: 10,
    question: "Base Mainnet launched publicly in which year?",
    options: ["2021", "2023"],
    correctOption: 1,
  },
  {
    id: 11,
    question: "What is Base Mainnet's chain ID?",
    options: ["8453", "84532"],
    correctOption: 0,
  },
  {
    id: 12,
    question: "What is Base Sepolia's chain ID?",
    options: ["84532", "8453"],
    correctOption: 0,
  },
  {
    id: 13,
    question: "What hexadecimal chain ID represents Base Mainnet?",
    options: ["0x2105", "0x14a34"],
    correctOption: 0,
  },
  {
    id: 14,
    question: "What hexadecimal chain ID represents Base Sepolia?",
    options: ["0x14a34", "0x2105"],
    correctOption: 0,
  },
  {
    id: 15,
    question: "Which JSON-RPC method returns the current chain ID?",
    options: ["eth_chainId", "eth_blockNumber"],
    correctOption: 0,
  },
  {
    id: 16,
    question: "Base Sepolia is primarily intended for what?",
    options: ["Testing", "Mainnet settlement"],
    correctOption: 0,
  },
  {
    id: 17,
    question: "Which network is the L1 beneath Base?",
    options: ["Ethereum", "Bitcoin"],
    correctOption: 0,
  },
  {
    id: 18,
    question: "Base executes Ethereum-compatible smart contracts using what?",
    options: ["EVM", "JVM"],
    correctOption: 0,
  },
  {
    id: 19,
    question: "What does EVM stand for?",
    options: ["Ethereum Virtual Machine", "Ethereum Validator Module"],
    correctOption: 0,
  },
  {
    id: 20,
    question: "The EVM is best described as what?",
    options: ["A computation environment", "A wallet application"],
    correctOption: 0,
  },
  {
    id: 21,
    question: "What does gas measure in EVM execution?",
    options: ["Computational effort", "Token ownership"],
    correctOption: 0,
  },
  {
    id: 22,
    question: "Which unit is the smallest denomination of ETH?",
    options: ["wei", "gwei"],
    correctOption: 0,
  },
  {
    id: 23,
    question: "How many wei are in 1 ETH?",
    options: ["10^18", "10^9"],
    correctOption: 0,
  },
  {
    id: 24,
    question: "Which Ethereum account type is controlled by private keys?",
    options: ["EOA", "Contract account"],
    correctOption: 0,
  },
  {
    id: 25,
    question: "Which Ethereum account type is controlled by deployed code?",
    options: ["Contract account", "EOA"],
    correctOption: 0,
  },
  {
    id: 26,
    question: "Can an EOA initiate an Ethereum transaction?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 27,
    question: "Does a contract account have its own private key?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 28,
    question: "What does a wallet primarily provide?",
    options: ["An interface to an account", "A new consensus mechanism"],
    correctOption: 0,
  },
  {
    id: 29,
    question: "What is a transaction on Ethereum?",
    options: ["A signed instruction", "A block explorer page"],
    correctOption: 0,
  },
  {
    id: 30,
    question: "Which transaction field identifies the recipient?",
    options: ["to", "nonce"],
    correctOption: 0,
  },
  {
    id: 31,
    question: "Which transaction field is a sequential account counter?",
    options: ["nonce", "value"],
    correctOption: 0,
  },
  {
    id: 32,
    question: "Which transaction field can carry arbitrary call data?",
    options: ["input data", "chain name"],
    correctOption: 0,
  },
  {
    id: 33,
    question: "What does gasLimit specify?",
    options: ["Maximum gas units usable", "Exact ETH transfer amount"],
    correctOption: 0,
  },
  {
    id: 34,
    question: "Does unused gas from a transaction's gas limit get charged as if it were used?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 35,
    question: "What is generated when a transaction is submitted?",
    options: ["Transaction hash", "Private key"],
    correctOption: 0,
  },
  {
    id: 36,
    question: "Where can a pending transaction wait before block inclusion?",
    options: ["Transaction pool", "Contract storage"],
    correctOption: 0,
  },
  {
    id: 37,
    question: "What must happen for a transaction to become part of the chain?",
    options: ["It must be included in a block", "It must create a token"],
    correctOption: 0,
  },
  {
    id: 38,
    question: "A transaction sent to a contract can trigger what?",
    options: ["Contract code", "A new private key"],
    correctOption: 0,
  },
  {
    id: 39,
    question: "What is a smart contract?",
    options: ["A program at a blockchain address", "A hardware wallet"],
    correctOption: 0,
  },
  {
    id: 40,
    question: "Does reading contract state normally create a transaction?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 41,
    question: "Does an eth_call normally change blockchain state?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 42,
    question: "Does writing contract state require a transaction?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 43,
    question: "Which Solidity function modifier indicates no state modification?",
    options: ["view", "payable"],
    correctOption: 0,
  },
  {
    id: 44,
    question: "Which Solidity function modifier indicates no state read or write?",
    options: ["pure", "payable"],
    correctOption: 0,
  },
  {
    id: 45,
    question: "What does ABI stand for in smart-contract interaction?",
    options: ["Application Binary Interface", "Automated Block Index"],
    correctOption: 0,
  },
  {
    id: 46,
    question: "What does a contract ABI describe?",
    options: ["How to encode and decode contract interactions", "A wallet's seed phrase"],
    correctOption: 0,
  },
  {
    id: 47,
    question: "Which language is commonly used for EVM smart contracts?",
    options: ["Solidity", "SQL"],
    correctOption: 0,
  },
  {
    id: 48,
    question: "What executes EVM smart-contract bytecode?",
    options: ["EVM", "DNS"],
    correctOption: 0,
  },
  {
    id: 49,
    question: "The EVM is primarily what kind of machine?",
    options: ["Stack machine", "Relational database"],
    correctOption: 0,
  },
  {
    id: 50,
    question: "What is the EVM's native word size?",
    options: ["256 bits", "64 bits"],
    correctOption: 0,
  },
  {
    id: 51,
    question: "Which EVM data area persists between transactions?",
    options: ["Storage", "Memory"],
    correctOption: 0,
  },
  {
    id: 52,
    question: "Does EVM memory persist between separate transactions?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 53,
    question: "Which opcodes are associated with transient storage?",
    options: ["MINT and BURN", "TSTORE and TLOAD"],
    correctOption: 1,
  },
  {
    id: 54,
    question: "When is EVM transient storage cleared?",
    options: ["Only when a contract is destroyed", "At the end of the transaction"],
    correctOption: 1,
  },
  {
    id: 55,
    question: "What is a blockchain state transition?",
    options: ["A wallet backup", "A change from one valid state to another"],
    correctOption: 1,
  },
  {
    id: 56,
    question: "What cryptographic action authorizes a normal EOA transaction?",
    options: ["Mining a private key", "Signing"],
    correctOption: 1,
  },
  {
    id: 57,
    question: "What should remain secret in an EOA key pair?",
    options: ["Public address", "Private key"],
    correctOption: 1,
  },
  {
    id: 58,
    question: "Can a public Ethereum address be shared for receiving assets?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 59,
    question: "Which standard is commonly used for fungible tokens?",
    options: ["ERC-721", "ERC-20"],
    correctOption: 1,
  },
  {
    id: 60,
    question: "Which standard is commonly used for non-fungible tokens?",
    options: ["ERC-20", "ERC-721"],
    correctOption: 1,
  },
  {
    id: 61,
    question: "Which standard can manage multiple token types in one contract?",
    options: ["ERC-20 only", "ERC-1155"],
    correctOption: 1,
  },
  {
    id: 62,
    question: "Can ERC-1155 represent fungible and non-fungible token types?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 63,
    question: "Which ERC-20 function commonly reports an account's token balance?",
    options: ["ownerOf", "balanceOf"],
    correctOption: 1,
  },
  {
    id: 64,
    question: "Which ERC-20 mechanism lets another account spend an approved amount?",
    options: ["Block height", "Allowance"],
    correctOption: 1,
  },
  {
    id: 65,
    question: "Which ERC-721 value identifies a particular token?",
    options: ["Gas price", "Token ID"],
    correctOption: 1,
  },
  {
    id: 66,
    question: "Which standard is designed around individually identifiable NFTs?",
    options: ["ERC-20", "ERC-721"],
    correctOption: 1,
  },
  {
    id: 67,
    question: "Which standard supports batch transfers of multiple token IDs?",
    options: ["ERC-20", "ERC-1155"],
    correctOption: 1,
  },
  {
    id: 68,
    question: "What does NFT stand for?",
    options: ["Network Fee Transfer", "Non-Fungible Token"],
    correctOption: 1,
  },
  {
    id: 69,
    question: "What does 'fungible' mean for token units?",
    options: ["Every unit must be unique", "They are interchangeable"],
    correctOption: 1,
  },
  {
    id: 70,
    question: "What does Layer 2 primarily aim to improve?",
    options: ["Private-key length", "Scalability"],
    correctOption: 1,
  },
  {
    id: 71,
    question: "Where do optimistic rollups execute transactions relative to Ethereum L1?",
    options: ["Inside Bitcoin blocks", "On an L2 execution environment"],
    correctOption: 1,
  },
  {
    id: 72,
    question: "Where do Ethereum rollups publish data used for L1-backed verification?",
    options: ["A private spreadsheet", "Ethereum"],
    correctOption: 1,
  },
  {
    id: 73,
    question: "Are optimistic rollups a type of Layer 2?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 74,
    question: "What does a rollup do with many transactions?",
    options: ["Deletes them", "Batches them"],
    correctOption: 1,
  },
  {
    id: 75,
    question: "Which Ethereum upgrade activated blob-carrying transactions?",
    options: ["The Merge", "Dencun"],
    correctOption: 1,
  },
  {
    id: 76,
    question: "Which EIP introduced blob-carrying transactions?",
    options: ["EIP-20", "EIP-4844"],
    correctOption: 1,
  },
  {
    id: 77,
    question: "What are blobs especially useful for?",
    options: ["Storing private keys", "Rollup data availability"],
    correctOption: 1,
  },
  {
    id: 78,
    question: "Compared with permanent calldata, blob data is designed to be what?",
    options: ["A wallet password", "Temporary"],
    correctOption: 1,
  },
  {
    id: 79,
    question: "Why are blobs useful to Layer 2 rollups?",
    options: ["They remove the need for signatures", "They provide cheaper data publication"],
    correctOption: 1,
  },
  {
    id: 80,
    question: "What does L1 refer to in Base's architecture?",
    options: ["Local wallet cache", "Ethereum base layer"],
    correctOption: 1,
  },
  {
    id: 81,
    question: "What does L2 refer to in Base's architecture?",
    options: ["A second private key", "A scaling layer above Ethereum"],
    correctOption: 1,
  },
  {
    id: 82,
    question: "In Base's rollup architecture, where is the L2 chain ultimately derived from?",
    options: ["Ethereum L1 data", "A private database"],
    correctOption: 0,
  },
  {
    id: 83,
    question: "What can L1 deposit transactions do in Base's derivation process?",
    options: ["Bring L1-originated actions into L2", "Reveal a user's seed phrase"],
    correctOption: 0,
  },
  {
    id: 84,
    question: "Can an Ethereum-style address begin with 0x?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 85,
    question: "How many hexadecimal characters are in an Ethereum address after 0x?",
    options: ["64", "40"],
    correctOption: 1,
  },
  {
    id: 86,
    question: "Which RPC method is commonly used for read-only contract calls?",
    options: ["eth_sendRawTransaction", "eth_call"],
    correctOption: 1,
  },
  {
    id: 87,
    question: "Which RPC method broadcasts a signed raw transaction?",
    options: ["eth_chainId", "eth_sendRawTransaction"],
    correctOption: 1,
  },
  {
    id: 88,
    question: "What is a block explorer mainly used for?",
    options: ["Recovering lost private keys", "Inspecting onchain activity"],
    correctOption: 1,
  },
  {
    id: 89,
    question: "Can a transaction hash be used to look up transaction details?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 90,
    question: "Does a successful contract write have to transfer ETH?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 91,
    question: "Can a zero-ETH transaction still call a smart contract?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 92,
    question: "Why must Base's derivation pipeline handle Ethereum L1 reorganizations?",
    options: ["To reconcile L2 derivation with the canonical L1 chain", "To change wallet passwords"],
    correctOption: 0,
  },
  {
    id: 93,
    question: "Should testnet ETH be treated as mainnet ETH with real monetary value?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 94,
    question: "What does 'onchain' generally mean?",
    options: ["Stored only in browser memory", "Recorded or executed on a blockchain"],
    correctOption: 1,
  },
  {
    id: 95,
    question: "What does 'offchain' generally mean?",
    options: ["Inside every Ethereum block", "Outside blockchain state"],
    correctOption: 1,
  },
  {
    id: 96,
    question: "What does Base's SystemConfig contract communicate to the L2 derivation process?",
    options: ["Rollup configuration changes", "NFT floor prices"],
    correctOption: 0,
  },
  {
    id: 97,
    question: "Why is EVM compatibility useful to Base developers?",
    options: ["It guarantees zero gas fees", "Ethereum tooling and contracts are easier to reuse"],
    correctOption: 1,
  },
  {
    id: 98,
    question: "Does EVM compatibility mean Base is Ethereum L1 itself?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 99,
    question: "Can the same Ethereum address format be used on multiple EVM networks?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 100,
    question: "Does sharing an address format mean all EVM networks share the same state?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 101,
    question: "Which consensus mechanism does Ethereum use today?",
    options: ["Proof-of-Stake", "Proof-of-Work"],
    correctOption: 0,
  },
  {
    id: 102,
    question: "What are Ethereum validators responsible for?",
    options: ["Choosing wallet passwords", "Proposing and attesting to blocks"],
    correctOption: 1,
  },
  {
    id: 103,
    question: "What asset do Ethereum validators stake?",
    options: ["ETH", "BTC"],
    correctOption: 0,
  },
  {
    id: 104,
    question: "What event moved Ethereum from Proof-of-Work to Proof-of-Stake?",
    options: ["Dencun", "The Merge"],
    correctOption: 1,
  },
  {
    id: 105,
    question: "Did The Merge itself create Ethereum Layer 2 networks?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 106,
    question: "What is a block in Ethereum?",
    options: ["A list of seed phrases", "A batch of transactions and related data"],
    correctOption: 1,
  },
  {
    id: 107,
    question: "What does block number indicate?",
    options: ["A block's position in the chain", "A wallet's token balance"],
    correctOption: 0,
  },
  {
    id: 108,
    question: "What does a block hash identify?",
    options: ["A private key", "A particular block"],
    correctOption: 1,
  },
  {
    id: 109,
    question: "Why does each block reference a parent block?",
    options: ["To link blocks into an ordered chain", "To generate wallet addresses"],
    correctOption: 0,
  },
  {
    id: 110,
    question: "What is the genesis block?",
    options: ["The latest finalized block", "The first block in a blockchain"],
    correctOption: 1,
  },
  {
    id: 111,
    question: "What does transaction finality mean?",
    options: ["The transaction is extremely unlikely to be reverted", "The transaction has zero gas cost"],
    correctOption: 0,
  },
  {
    id: 112,
    question: "What is an Ethereum node?",
    options: ["A type of NFT", "Software that participates in the Ethereum network"],
    correctOption: 1,
  },
  {
    id: 113,
    question: "What does an execution client do?",
    options: ["Processes transactions and maintains execution state", "Stores a user's seed phrase for them"],
    correctOption: 0,
  },
  {
    id: 114,
    question: "What does a consensus client do?",
    options: ["Compiles Solidity into JavaScript", "Participates in Ethereum's Proof-of-Stake consensus"],
    correctOption: 1,
  },
  {
    id: 115,
    question: "Can a blockchain node independently verify protocol rules?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 116,
    question: "What does decentralization reduce dependence on?",
    options: ["Cryptographic signatures", "A single controlling intermediary"],
    correctOption: 1,
  },
  {
    id: 117,
    question: "What is a peer-to-peer network?",
    options: ["A network where participants communicate directly", "A network with only one server"],
    correctOption: 0,
  },
  {
    id: 118,
    question: "What is the purpose of a blockchain's consensus mechanism?",
    options: ["Creating website CSS", "Agreeing on valid chain state"],
    correctOption: 1,
  },
  {
    id: 119,
    question: "What does 'permissionless' commonly mean in public blockchains?",
    options: ["Participation does not require approval from one central gatekeeper", "Every transaction is free"],
    correctOption: 0,
  },
  {
    id: 120,
    question: "Does public blockchain data mean private keys are public?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 121,
    question: "What is a seed phrase used for in many wallets?",
    options: ["Recovering wallet keys", "Selecting a chain ID"],
    correctOption: 0,
  },
  {
    id: 122,
    question: "Should a seed phrase be entered into an unsolicited website?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 123,
    question: "What is phishing in crypto?",
    options: ["Deception intended to steal credentials or assets", "A method of compressing blocks"],
    correctOption: 0,
  },
  {
    id: 124,
    question: "What is wallet signing?",
    options: ["Publishing a private key", "Using a private key to authorize or authenticate"],
    correctOption: 1,
  },
  {
    id: 125,
    question: "Can signing a malicious transaction put assets at risk?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 126,
    question: "Why should users inspect transaction details before signing?",
    options: ["To increase the chain ID", "To understand what they are authorizing"],
    correctOption: 1,
  },
  {
    id: 127,
    question: "What does token approval usually authorize?",
    options: ["A spender to use tokens within an allowance", "A validator to reveal a seed phrase"],
    correctOption: 0,
  },
  {
    id: 128,
    question: "Can an unlimited token approval create additional risk?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 129,
    question: "What is a smart-contract audit intended to do?",
    options: ["Identify security issues in contract code", "Guarantee token price appreciation"],
    correctOption: 0,
  },
  {
    id: 130,
    question: "Does a smart-contract audit guarantee a contract has no bugs?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 131,
    question: "What is a reentrancy vulnerability?",
    options: ["External control flow re-enters a contract before expected state handling completes", "A wallet changes its chain ID"],
    correctOption: 0,
  },
  {
    id: 132,
    question: "What Solidity pattern helps prevent some reentrancy issues?",
    options: ["Proof-of-Work", "Checks-Effects-Interactions"],
    correctOption: 1,
  },
  {
    id: 133,
    question: "What does access control restrict in a smart contract?",
    options: ["Who can perform privileged actions", "Which block explorer users may visit"],
    correctOption: 0,
  },
  {
    id: 134,
    question: "What is a multisig wallet?",
    options: ["A wallet with multiple chain IDs", "A wallet requiring multiple approvals under its policy"],
    correctOption: 1,
  },
  {
    id: 135,
    question: "Why can multisig improve treasury security?",
    options: ["It reduces reliance on a single signing key", "It eliminates all smart-contract risk"],
    correctOption: 0,
  },
  {
    id: 136,
    question: "What is a hardware wallet designed to protect?",
    options: ["Public block data", "Private-key signing material"],
    correctOption: 1,
  },
  {
    id: 137,
    question: "Does a hardware wallet make every transaction safe automatically?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 138,
    question: "What is a contract address?",
    options: ["A validator's IP address", "The blockchain address of deployed contract code"],
    correctOption: 1,
  },
  {
    id: 139,
    question: "What happens when smart-contract code is deployed?",
    options: ["It becomes associated with an onchain contract address", "It becomes a seed phrase"],
    correctOption: 0,
  },
  {
    id: 140,
    question: "Can two contracts interact with each other onchain?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 141,
    question: "What is an event in an EVM smart contract commonly used for?",
    options: ["Emitting log data", "Changing a private key"],
    correctOption: 0,
  },
  {
    id: 142,
    question: "Are EVM event logs the same as contract storage?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 143,
    question: "What does an indexed event parameter help with?",
    options: ["Filtering logs", "Reducing an address to four bytes"],
    correctOption: 0,
  },
  {
    id: 144,
    question: "What is a function selector in EVM calldata derived from?",
    options: ["The wallet's ETH balance", "The function signature"],
    correctOption: 1,
  },
  {
    id: 145,
    question: "How long is a standard EVM function selector?",
    options: ["4 bytes", "32 bytes"],
    correctOption: 0,
  },
  {
    id: 146,
    question: "What does calldata contain in a contract call?",
    options: ["The caller's private key", "Encoded function call data"],
    correctOption: 1,
  },
  {
    id: 147,
    question: "Is calldata mutable by the called Solidity function?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 148,
    question: "What does msg.sender represent in Solidity?",
    options: ["The current block number", "The immediate caller"],
    correctOption: 1,
  },
  {
    id: 149,
    question: "What does msg.value represent in a payable Solidity call?",
    options: ["The amount of native currency sent with the call", "The transaction nonce"],
    correctOption: 0,
  },
  {
    id: 150,
    question: "Which Solidity keyword allows a function to receive ETH?",
    options: ["indexed", "payable"],
    correctOption: 1,
  },
  {
    id: 151,
    question: "What happens if a nonpayable function is called with ETH?",
    options: ["The call normally reverts", "The ETH is automatically converted to a token"],
    correctOption: 0,
  },
  {
    id: 152,
    question: "What does revert do in EVM execution?",
    options: ["Deletes the blockchain", "Aborts the current execution and rolls back its state changes"],
    correctOption: 1,
  },
  {
    id: 153,
    question: "If a transaction reverts, is gas still generally consumed?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 154,
    question: "What is a custom error in Solidity useful for?",
    options: ["Generating a new private key", "Returning structured revert information efficiently"],
    correctOption: 1,
  },
  {
    id: 155,
    question: "What does require commonly do in Solidity?",
    options: ["Checks a condition and reverts if it fails", "Creates a new blockchain"],
    correctOption: 0,
  },
  {
    id: 156,
    question: "What is contract storage organized into?",
    options: ["HTML elements", "32-byte slots"],
    correctOption: 1,
  },
  {
    id: 157,
    question: "What is a mapping in Solidity?",
    options: ["A key-value data structure", "A consensus algorithm"],
    correctOption: 0,
  },
  {
    id: 158,
    question: "Can Solidity mappings be directly enumerated without separately tracking keys?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 159,
    question: "What is an immutable Solidity variable?",
    options: ["A value assigned at construction and then fixed", "A value that changes every block"],
    correctOption: 0,
  },
  {
    id: 160,
    question: "What is a constant Solidity variable?",
    options: ["A wallet-generated nonce", "A compile-time fixed value"],
    correctOption: 1,
  },
  {
    id: 161,
    question: "What is a constructor in Solidity?",
    options: ["Code run when a contract is deployed", "Code run for every view call"],
    correctOption: 0,
  },
  {
    id: 162,
    question: "What does msg.data contain?",
    options: ["The current block hash only", "Complete calldata of the current call"],
    correctOption: 1,
  },
  {
    id: 163,
    question: "What does block.timestamp represent?",
    options: ["The timestamp associated with the current block", "The user's local computer time"],
    correctOption: 0,
  },
  {
    id: 164,
    question: "Should block.timestamp be treated as a source of perfectly unpredictable randomness?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 165,
    question: "What is a proxy contract commonly used for?",
    options: ["Upgradeability or indirection", "Generating Proof-of-Work"],
    correctOption: 0,
  },
  {
    id: 166,
    question: "In a proxy pattern, where is logic often executed?",
    options: ["In a DNS server", "In an implementation contract via delegatecall"],
    correctOption: 1,
  },
  {
    id: 167,
    question: "What does delegatecall preserve from the proxy's context?",
    options: ["Storage context", "The implementation's separate storage only"],
    correctOption: 0,
  },
  {
    id: 168,
    question: "Why must upgradeable contracts manage storage layout carefully?",
    options: ["Storage is always deleted after upgrades", "Layout changes can corrupt interpreted state"],
    correctOption: 1,
  },
  {
    id: 169,
    question: "What is contract verification on a block explorer?",
    options: ["Publishing source information that matches deployed bytecode", "Giving the explorer control of the contract"],
    correctOption: 0,
  },
  {
    id: 170,
    question: "Does verified source code mean the contract is automatically safe?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 171,
    question: "What is an oracle used for in smart contracts?",
    options: ["Bringing external data into onchain applications", "Storing seed phrases"],
    correctOption: 0,
  },
  {
    id: 172,
    question: "Why can oracle design matter for DeFi security?",
    options: ["Oracles eliminate all price volatility", "Contracts may depend on oracle data for financial decisions"],
    correctOption: 1,
  },
  {
    id: 173,
    question: "What is a decentralized exchange commonly called?",
    options: ["DEX", "DNS"],
    correctOption: 0,
  },
  {
    id: 174,
    question: "What does an AMM use to facilitate decentralized trading?",
    options: ["Email servers", "Liquidity pools and pricing rules"],
    correctOption: 1,
  },
  {
    id: 175,
    question: "What does AMM stand for?",
    options: ["Automated Market Maker", "Automatic Mining Module"],
    correctOption: 0,
  },
  {
    id: 176,
    question: "What is a liquidity pool?",
    options: ["A list of validator passwords", "Assets supplied to a protocol for trading or other functions"],
    correctOption: 1,
  },
  {
    id: 177,
    question: "What is slippage in a token swap?",
    options: ["Difference between expected and executed price", "The number of wallet accounts"],
    correctOption: 0,
  },
  {
    id: 178,
    question: "Can larger trades experience more price impact in a finite liquidity pool?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 179,
    question: "What is a stablecoin designed to do?",
    options: ["Track a relatively stable reference value", "Guarantee investment profit"],
    correctOption: 0,
  },
  {
    id: 180,
    question: "USDC is designed to track which currency?",
    options: ["Japanese yen", "U.S. dollar"],
    correctOption: 1,
  },
  {
    id: 181,
    question: "Is a stablecoin necessarily identical in risk to cash held in a bank account?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 182,
    question: "What is bridging in crypto?",
    options: ["Changing a seed phrase into a password", "Moving or representing assets/data across networks"],
    correctOption: 1,
  },
  {
    id: 183,
    question: "Why should users verify the destination network when bridging?",
    options: ["Assets can end up on an unintended network", "It changes the Ethereum consensus mechanism"],
    correctOption: 0,
  },
  {
    id: 184,
    question: "What does 'canonical bridge' generally refer to?",
    options: ["Any random token swap website", "A bridge tied to a network's core protocol path"],
    correctOption: 1,
  },
  {
    id: 185,
    question: "Can bridges introduce additional smart-contract or trust risks?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 186,
    question: "What is wrapping a token?",
    options: ["Encrypting a block explorer", "Representing an asset in another tokenized form"],
    correctOption: 1,
  },
  {
    id: 187,
    question: "What is WETH?",
    options: ["An ERC-20 representation of ETH", "A Base-native gas token"],
    correctOption: 0,
  },
  {
    id: 188,
    question: "Why is WETH useful in many DeFi contracts?",
    options: ["It removes all transaction fees", "It gives ETH an ERC-20-compatible interface"],
    correctOption: 1,
  },
  {
    id: 189,
    question: "Can WETH normally be converted back to ETH through its wrapping contract?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 190,
    question: "What does composability mean in DeFi?",
    options: ["Every protocol uses the same private key", "Protocols can interact and build on one another"],
    correctOption: 1,
  },
  {
    id: 191,
    question: "What is a DAO?",
    options: ["A blockchain-based organizational coordination structure", "A type of EVM opcode"],
    correctOption: 0,
  },
  {
    id: 192,
    question: "What does governance voting commonly allow token or membership holders to do?",
    options: ["Recover any lost private key", "Participate in protocol decisions"],
    correctOption: 1,
  },
  {
    id: 193,
    question: "Does owning a governance token always grant legal ownership of a company?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 194,
    question: "What is account abstraction intended to improve?",
    options: ["The maximum length of a domain name", "Programmability and flexibility of blockchain accounts"],
    correctOption: 1,
  },
  {
    id: 195,
    question: "What can a smart account support beyond a basic EOA?",
    options: ["Programmable authorization rules", "Proof-of-Work mining on Base"],
    correctOption: 0,
  },
  {
    id: 196,
    question: "What is a bundler in ERC-4337?",
    options: ["A service that stores private keys publicly", "An actor that packages UserOperations for execution"],
    correctOption: 1,
  },
  {
    id: 197,
    question: "What is a UserOperation in ERC-4337?",
    options: ["A request describing an action by a smart account", "An Ethereum block header"],
    correctOption: 0,
  },
  {
    id: 198,
    question: "What can a paymaster do in ERC-4337?",
    options: ["Change Ethereum's chain ID", "Sponsor or customize gas payment under rules"],
    correctOption: 1,
  },
  {
    id: 199,
    question: "Does account abstraction require users to expose their private keys?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 200,
    question: "What is gas sponsorship?",
    options: ["A validator reveals its signing key", "A third party covers transaction gas under specified conditions"],
    correctOption: 1,
  },
  {
    id: 201,
    question: "What does HTTPS add to ordinary HTTP?",
    options: ["Encrypted transport using TLS", "A blockchain consensus layer"],
    correctOption: 0,
  },
  {
    id: 202,
    question: "What is JSON commonly used for in web3 APIs?",
    options: ["Private-key generation", "Structured data exchange"],
    correctOption: 1,
  },
  {
    id: 203,
    question: "What does JSON-RPC provide?",
    options: ["A request-response protocol for calling remote methods", "A token standard"],
    correctOption: 0,
  },
  {
    id: 204,
    question: "In JSON-RPC, what identifies the method to call?",
    options: ["The favicon", "The method field"],
    correctOption: 1,
  },
  {
    id: 205,
    question: "What does an RPC endpoint let a dapp communicate with?",
    options: ["A blockchain node or node service", "A hardware display cable"],
    correctOption: 0,
  },
  {
    id: 206,
    question: "Can a dapp use more than one RPC provider for resilience?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 207,
    question: "Why can RPC rate limits matter to an app?",
    options: ["Too many requests may be throttled", "They change contract ownership"],
    correctOption: 0,
  },
  {
    id: 208,
    question: "What is a WebSocket useful for in blockchain apps?",
    options: ["Generating seed phrases", "Receiving ongoing updates"],
    correctOption: 1,
  },
  {
    id: 209,
    question: "Compared with HTTP polling, WebSockets can provide what?",
    options: ["Persistent real-time communication", "A new token standard"],
    correctOption: 0,
  },
  {
    id: 210,
    question: "What does a frontend dapp typically use a wallet provider for?",
    options: ["Changing Ethereum consensus rules", "Requesting accounts and signatures"],
    correctOption: 1,
  },
  {
    id: 211,
    question: "What does EIP-1193 standardize?",
    options: ["An Ethereum provider interface for JavaScript apps", "NFT image dimensions"],
    correctOption: 0,
  },
  {
    id: 212,
    question: "Which EIP-1193 method is commonly requested to access user accounts?",
    options: ["eth_getCode", "eth_requestAccounts"],
    correctOption: 1,
  },
  {
    id: 213,
    question: "What does wallet_switchEthereumChain request?",
    options: ["Switching the wallet's active chain", "Transferring an NFT"],
    correctOption: 0,
  },
  {
    id: 214,
    question: "What does wallet_addEthereumChain request?",
    options: ["Deploying a smart contract", "Adding a network configuration to a wallet"],
    correctOption: 1,
  },
  {
    id: 215,
    question: "Should a dapp assume a user is always connected to the intended chain?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 216,
    question: "Why should a dapp verify chain ID before sending a transaction?",
    options: ["To reveal the user's private key", "To avoid acting on the wrong network"],
    correctOption: 1,
  },
  {
    id: 217,
    question: "What does eth_getBalance return?",
    options: ["An address's native-currency balance", "An ERC-721 token URI"],
    correctOption: 0,
  },
  {
    id: 218,
    question: "What does eth_getCode return for an address?",
    options: ["The account's seed phrase", "The EVM bytecode stored at that address"],
    correctOption: 1,
  },
  {
    id: 219,
    question: "What does eth_getTransactionReceipt provide?",
    options: ["The result and metadata of a mined transaction", "A wallet recovery phrase"],
    correctOption: 0,
  },
  {
    id: 220,
    question: "What receipt field commonly indicates success or failure?",
    options: ["favicon", "status"],
    correctOption: 1,
  },
  {
    id: 221,
    question: "What does eth_estimateGas help estimate?",
    options: ["Gas needed for a transaction", "A token's future price"],
    correctOption: 0,
  },
  {
    id: 222,
    question: "Can gas estimation fail if the simulated call would revert?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 223,
    question: "What does eth_blockNumber return?",
    options: ["The latest known block number", "The chain's private key"],
    correctOption: 0,
  },
  {
    id: 224,
    question: "What does eth_getLogs retrieve?",
    options: ["Wallet passwords", "Event logs matching filters"],
    correctOption: 1,
  },
  {
    id: 225,
    question: "Why do apps use event logs?",
    options: ["To index and react to onchain activity", "To alter historical blocks"],
    correctOption: 0,
  },
  {
    id: 226,
    question: "What is an indexer in a blockchain application?",
    options: ["A device that signs transactions offline", "A service that organizes onchain data for efficient queries"],
    correctOption: 1,
  },
  {
    id: 227,
    question: "Why might an app use an indexer instead of scanning every block itself?",
    options: ["Faster and easier querying", "To bypass cryptographic signatures"],
    correctOption: 0,
  },
  {
    id: 228,
    question: "Can an indexer replace the blockchain as the source of truth for settlement?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 229,
    question: "What does deterministic execution mean for smart contracts?",
    options: ["The same valid inputs and state produce the same execution result", "Contract results depend on a user's screen size"],
    correctOption: 0,
  },
  {
    id: 230,
    question: "Why must blockchain execution be deterministic?",
    options: ["Wallets need different private keys each block", "Nodes need to agree on state transitions"],
    correctOption: 1,
  },
  {
    id: 231,
    question: "What is a contract's runtime bytecode?",
    options: ["Code stored for execution after deployment", "A website's CSS"],
    correctOption: 0,
  },
  {
    id: 232,
    question: "What is creation bytecode used for?",
    options: ["Signing every user transaction", "Deploying and initializing a contract"],
    correctOption: 1,
  },
  {
    id: 233,
    question: "What is CREATE2 known for enabling?",
    options: ["Predictable contract addresses from specified inputs", "Free gas on every transaction"],
    correctOption: 0,
  },
  {
    id: 234,
    question: "Can a future CREATE2 contract address be computed before the contract is deployed?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 235,
    question: "What is a factory contract?",
    options: ["A contract that deploys other contracts", "A validator that produces NFTs"],
    correctOption: 0,
  },
  {
    id: 236,
    question: "Why are factory contracts useful?",
    options: ["They reveal users' private keys", "They standardize repeated deployments"],
    correctOption: 1,
  },
  {
    id: 237,
    question: "What is a contract interface in Solidity?",
    options: ["A declaration of callable external functions without implementation", "A block explorer theme"],
    correctOption: 0,
  },
  {
    id: 238,
    question: "What is inheritance in Solidity?",
    options: ["Moving tokens between chains", "A contract deriving behavior from another contract"],
    correctOption: 1,
  },
  {
    id: 239,
    question: "What is a Solidity library?",
    options: ["Reusable code intended to be called by contracts", "A list of wallet seed phrases"],
    correctOption: 0,
  },
  {
    id: 240,
    question: "What does internal visibility mean in Solidity?",
    options: ["Callable only from a block explorer", "Callable within the contract and derived contracts"],
    correctOption: 1,
  },
  {
    id: 241,
    question: "What does external visibility mean for a Solidity function?",
    options: ["Designed to be called from outside the contract", "The function can only run offchain"],
    correctOption: 0,
  },
  {
    id: 242,
    question: "What does public visibility allow for a Solidity function?",
    options: ["Calls only from validators", "Calls from inside and outside the contract"],
    correctOption: 1,
  },
  {
    id: 243,
    question: "What does private visibility restrict in Solidity?",
    options: ["Access to the defining contract's scope", "Reading public blockchain data"],
    correctOption: 0,
  },
  {
    id: 244,
    question: "Does Solidity private visibility make blockchain data secret?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 245,
    question: "Why is sensitive information unsafe to store unencrypted on a public blockchain?",
    options: ["Blockchain state can be publicly inspected", "Storage automatically deletes itself"],
    correctOption: 0,
  },
  {
    id: 246,
    question: "What is a Merkle tree useful for?",
    options: ["Generating a wallet password", "Efficiently proving membership in a dataset"],
    correctOption: 1,
  },
  {
    id: 247,
    question: "What is a Merkle root?",
    options: ["A compact commitment to a set of data", "A user's private key"],
    correctOption: 0,
  },
  {
    id: 248,
    question: "What does a Merkle proof demonstrate?",
    options: ["That a token price will rise", "That an item belongs to a committed dataset"],
    correctOption: 1,
  },
  {
    id: 249,
    question: "Can Merkle proofs reduce the amount of data a contract must store for an allowlist?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 250,
    question: "What is a cryptographic hash function designed to produce?",
    options: ["A reversible private-key backup", "A fixed-size digest from input data"],
    correctOption: 1,
  },
  {
    id: 251,
    question: "Is a cryptographic hash intended to be easily reversible?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 252,
    question: "What does keccak256 produce in Solidity?",
    options: ["A 20-bit wallet address", "A 256-bit hash"],
    correctOption: 1,
  },
  {
    id: 253,
    question: "Why are hashes useful for integrity checks?",
    options: ["Changes to input produce a different digest with overwhelming probability", "They guarantee zero gas fees"],
    correctOption: 0,
  },
  {
    id: 254,
    question: "What is a digital signature used to verify?",
    options: ["A website's screen resolution", "Authorization by a key holder"],
    correctOption: 1,
  },
  {
    id: 255,
    question: "Does verifying a signature require revealing the private key?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 256,
    question: "What is ECDSA used for in Ethereum?",
    options: ["Compressing NFT images", "Digital signatures"],
    correctOption: 1,
  },
  {
    id: 257,
    question: "What is secp256k1?",
    options: ["The elliptic curve used by Ethereum EOAs for ECDSA", "An ERC token standard"],
    correctOption: 0,
  },
  {
    id: 258,
    question: "What is a public key derived from?",
    options: ["A block explorer URL", "A private key"],
    correctOption: 1,
  },
  {
    id: 259,
    question: "What is an Ethereum address derived from for a standard EOA?",
    options: ["Its public key", "Its gas limit"],
    correctOption: 0,
  },
  {
    id: 260,
    question: "Can someone derive a user's private key from their Ethereum address using normal feasible computation?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 261,
    question: "What is message signing useful for besides transactions?",
    options: ["Proving control of an address", "Changing historical blocks"],
    correctOption: 0,
  },
  {
    id: 262,
    question: "What does EIP-712 define?",
    options: ["Blob storage duration", "Typed structured data signing"],
    correctOption: 1,
  },
  {
    id: 263,
    question: "Why is typed-data signing useful?",
    options: ["It can make signed data more structured and understandable", "It removes the need for keys"],
    correctOption: 0,
  },
  {
    id: 264,
    question: "Is an offchain signed message automatically an onchain transaction?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 265,
    question: "Can a smart contract verify certain offchain signatures onchain?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 266,
    question: "What is replay protection intended to prevent?",
    options: ["Viewing a transaction twice", "Reusing an authorization in an unintended context"],
    correctOption: 1,
  },
  {
    id: 267,
    question: "How can a nonce help with signed authorizations?",
    options: ["It makes each authorization uniquely consumable", "It increases token decimals"],
    correctOption: 0,
  },
  {
    id: 268,
    question: "What is a deadline field useful for in a signed authorization?",
    options: ["Choosing the chain's consensus mechanism", "Limiting how long it remains valid"],
    correctOption: 1,
  },
  {
    id: 269,
    question: "What is a token permit pattern designed to enable?",
    options: ["Approval through a signature", "Proof-of-Work mining"],
    correctOption: 0,
  },
  {
    id: 270,
    question: "Which EIP is widely associated with ERC-20 permit signatures?",
    options: ["EIP-721", "EIP-2612"],
    correctOption: 1,
  },
  {
    id: 271,
    question: "Can permit-style approvals reduce the need for a separate approval transaction?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 272,
    question: "What is a meta-transaction?",
    options: ["A transaction that changes a block's parent", "A transaction pattern where a relayer can submit a user's signed intent"],
    correctOption: 1,
  },
  {
    id: 273,
    question: "What is a relayer in a meta-transaction flow?",
    options: ["An entity that submits a transaction on behalf of a user", "A contract's private key"],
    correctOption: 0,
  },
  {
    id: 274,
    question: "Can a relayer pay gas while the user authorizes an action by signature?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 275,
    question: "What is a faucet on a testnet?",
    options: ["A service that distributes test tokens", "A mainnet yield guarantee"],
    correctOption: 0,
  },
  {
    id: 276,
    question: "Why are testnet faucets useful?",
    options: ["They convert test ETH into guaranteed mainnet ETH", "Developers can obtain test assets for experimentation"],
    correctOption: 1,
  },
  {
    id: 277,
    question: "Does Base Sepolia use the same chain ID as Base Mainnet?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 278,
    question: "Should a production app hard-code a testnet contract address for mainnet transactions?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 279,
    question: "Why should contract addresses be associated with the correct chain?",
    options: ["The same address can refer to different state or code across networks", "Addresses contain the chain ID inside them"],
    correctOption: 0,
  },
  {
    id: 280,
    question: "What is environment configuration commonly used for in a dapp?",
    options: ["Publishing seed phrases", "Separating network-specific settings"],
    correctOption: 1,
  },
  {
    id: 281,
    question: "What is an environment variable useful for?",
    options: ["Providing configurable values outside source logic", "Changing past blockchain transactions"],
    correctOption: 0,
  },
  {
    id: 282,
    question: "Should a frontend environment variable be assumed secret if it is bundled into browser code?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 283,
    question: "Why should true secrets stay on trusted server-side infrastructure?",
    options: ["Browser-delivered code can be inspected by users", "Servers do not use networks"],
    correctOption: 0,
  },
  {
    id: 284,
    question: "What is an API route in a web application?",
    options: ["An EVM opcode", "A server endpoint that handles requests"],
    correctOption: 1,
  },
  {
    id: 285,
    question: "Why might a dapp use a server API for signing application attestations?",
    options: ["To keep the signing key off the client", "To make the private key visible in the browser"],
    correctOption: 0,
  },
  {
    id: 286,
    question: "What is one main responsibility of a Base rollup node?",
    options: ["Deriving the L2 chain from L1 data", "Generating users' seed phrases"],
    correctOption: 0,
  },
  {
    id: 287,
    question: "What happens to an invalid sequencer batch when checked by a correct Base rollup node?",
    options: ["It is discarded", "It becomes finalized automatically"],
    correctOption: 0,
  },
  {
    id: 288,
    question: "What does Base's batcher submit for data availability?",
    options: ["Sequencer batch data", "Wallet recovery phrases"],
    correctOption: 0,
  },
  {
    id: 289,
    question: "Why does Base's derivation pipeline track L1 origins?",
    options: ["To connect L2 derivation to Ethereum L1 data", "To set token market prices"],
    correctOption: 0,
  },
  {
    id: 290,
    question: "What must Base derivation be able to recover from if Ethereum's canonical L1 chain reorganizes?",
    options: ["An L1 reorg", "A browser theme change"],
    correctOption: 0,
  },
  {
    id: 291,
    question: "Why must each sequencing epoch contain at least one L2 block in the OP Stack derivation rules?",
    options: ["So relevant L1 information is represented on L2", "So every wallet receives ETH"],
    correctOption: 0,
  },
  {
    id: 292,
    question: "What are PayloadAttributes used for in Base's derivation pipeline?",
    options: ["Describing inputs needed to build an L2 block", "Encrypting private keys"],
    correctOption: 0,
  },
  {
    id: 293,
    question: "What does Base's finalized L2 head reflect?",
    options: ["L2 blocks derived from finalized L1 data", "Only transactions stored in a browser"],
    correctOption: 0,
  },
  {
    id: 294,
    question: "What is a span batch designed to reduce?",
    options: ["Batching overhead when posting sequences of L2 blocks", "The length of Ethereum addresses"],
    correctOption: 0,
  },
  {
    id: 295,
    question: "Which Base upgrade introduced stricter frame and batch ordering rules?",
    options: ["Holocene", "The Merge"],
    correctOption: 0,
  },
  {
    id: 296,
    question: "Under Holocene derivation rules, what happens after certain invalid payloads?",
    options: ["They can be replaced by deposit-only payloads", "All historical L2 blocks are deleted"],
    correctOption: 0,
  },
  {
    id: 297,
    question: "What does the Base derivation pipeline do with batches before turning them into L2 blocks?",
    options: ["Validates and orders them according to protocol rules", "Converts them into wallet seed phrases"],
    correctOption: 0,
  },
  {
    id: 298,
    question: "Why can span batches be more efficient than repeating metadata for every L2 block?",
    options: ["They encode consecutive L2 blocks with less repeated overhead", "They remove the need for Ethereum"],
    correctOption: 0,
  },
  {
    id: 299,
    question: "What does a Base Flashblocks endpoint expose before normal block confirmation?",
    options: ["Pre-confirmed state updates", "A user's private key"],
    correctOption: 0,
  },
  {
    id: 300,
    question: "When querying a Base Flashblocks endpoint, which block tag can include pre-confirmed transactions?",
    options: ["pending", "earliest only"],
    correctOption: 0,
  },
  {
    id: 301,
    question: "What is the Superchain concept associated with?",
    options: ["A network of OP Stack chains designed for interoperability", "A single Ethereum wallet"],
    correctOption: 0,
  },
  {
    id: 302,
    question: "What is a channel frame in OP Stack batch submission?",
    options: ["A chunk of data belonging to a channel", "A wallet authentication factor"],
    correctOption: 0,
  },
  {
    id: 303,
    question: "What does Holocene's strict batch ordering aim to simplify?",
    options: ["L2 chain derivation", "Private-key generation"],
    correctOption: 0,
  },
  {
    id: 304,
    question: "What is an L2 sequencer primarily responsible for?",
    options: ["Generating users' seed phrases", "Ordering and processing L2 transactions"],
    correctOption: 1,
  },
  {
    id: 305,
    question: "Does an L2 sequencer replace Ethereum as Base's settlement layer?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 306,
    question: "Why does a rollup post data to Ethereum?",
    options: ["To store users' private keys", "To make transaction data available for verification"],
    correctOption: 1,
  },
  {
    id: 307,
    question: "What is data availability in a rollup context?",
    options: ["Ensuring data needed to reconstruct and verify state is accessible", "Keeping token prices unchanged"],
    correctOption: 0,
  },
  {
    id: 308,
    question: "What is an L2 batch?",
    options: ["A collection of wallet passwords", "A group of L2 transaction data submitted together"],
    correctOption: 1,
  },
  {
    id: 309,
    question: "What is an output root in an optimistic rollup context?",
    options: ["A commitment related to L2 state", "A user's recovery phrase"],
    correctOption: 0,
  },
  {
    id: 310,
    question: "What is a fault proof intended to establish?",
    options: ["That every transaction is free", "That a disputed state transition is invalid"],
    correctOption: 1,
  },
  {
    id: 311,
    question: "Why are optimistic rollups called 'optimistic'?",
    options: ["State transitions are accepted unless successfully challenged", "They assume token prices rise"],
    correctOption: 0,
  },
  {
    id: 312,
    question: "Does an optimistic rollup execute every L2 transaction directly on L1?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 313,
    question: "What is settlement in a rollup architecture?",
    options: ["Finalizing rollup state and disputes using the underlying chain", "Choosing a dapp's font"],
    correctOption: 0,
  },
  {
    id: 314,
    question: "What is the purpose of an L1 bridge contract in an L2 system?",
    options: ["Store browser cookies", "Coordinate asset/message movement between L1 and L2"],
    correctOption: 1,
  },
  {
    id: 315,
    question: "Can withdrawing through an optimistic-rollup canonical path involve a waiting period?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 316,
    question: "Why can an optimistic-rollup withdrawal require waiting?",
    options: ["The wallet must mine Bitcoin", "The protocol allows time for invalid claims to be challenged"],
    correctOption: 1,
  },
  {
    id: 317,
    question: "What is cross-domain messaging?",
    options: ["Communication between contracts or systems on different layers", "Sending an email between wallets"],
    correctOption: 0,
  },
  {
    id: 318,
    question: "Can an L1 contract send a message intended for an L2 contract through bridge infrastructure?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 319,
    question: "Why should cross-chain applications consider asynchronous execution?",
    options: ["Messages across chains may not complete immediately", "All chains share one synchronous state"],
    correctOption: 0,
  },
  {
    id: 320,
    question: "Does a bridge transfer necessarily mean the identical token contract exists on both chains?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 321,
    question: "What is token decimal metadata used for?",
    options: ["Displaying token units in human-readable form", "Determining blockchain consensus"],
    correctOption: 0,
  },
  {
    id: 322,
    question: "Does an ERC-20 token's decimals value change its raw integer accounting?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 323,
    question: "If a token has 6 decimals, what raw amount represents one whole token?",
    options: ["1,000,000", "100"],
    correctOption: 0,
  },
  {
    id: 324,
    question: "If a token has 18 decimals, what raw amount represents one whole token?",
    options: ["10^6", "10^18"],
    correctOption: 1,
  },
  {
    id: 325,
    question: "Why should apps avoid ordinary floating-point math for onchain token amounts?",
    options: ["Precision errors can occur", "Floating point changes chain ID"],
    correctOption: 0,
  },
  {
    id: 326,
    question: "What type is commonly used in JavaScript for exact large blockchain integers?",
    options: ["Float32", "BigInt"],
    correctOption: 1,
  },
  {
    id: 327,
    question: "What does hexadecimal notation use as its base?",
    options: ["16", "10"],
    correctOption: 0,
  },
  {
    id: 328,
    question: "Which characters can appear as hexadecimal digits?",
    options: ["0-9 and G-Z", "0-9 and A-F"],
    correctOption: 1,
  },
  {
    id: 329,
    question: "What does the 0x prefix conventionally indicate?",
    options: ["Hexadecimal data", "A decimal percentage"],
    correctOption: 0,
  },
  {
    id: 330,
    question: "How many bits are in one byte?",
    options: ["16", "8"],
    correctOption: 1,
  },
  {
    id: 331,
    question: "How many hexadecimal digits represent one byte?",
    options: ["2", "8"],
    correctOption: 0,
  },
  {
    id: 332,
    question: "How many bytes are in a 256-bit value?",
    options: ["256", "32"],
    correctOption: 1,
  },
  {
    id: 333,
    question: "How many bytes are in a standard Ethereum address?",
    options: ["20", "32"],
    correctOption: 0,
  },
  {
    id: 334,
    question: "What is ABI encoding used for?",
    options: ["Compressing website images", "Representing typed values as EVM call data"],
    correctOption: 1,
  },
  {
    id: 335,
    question: "What does ABI decoding do?",
    options: ["Interprets encoded EVM data as typed values", "Creates a validator key"],
    correctOption: 0,
  },
  {
    id: 336,
    question: "What is a bytes32 Solidity value?",
    options: ["A dynamic array of any size", "A fixed 32-byte value"],
    correctOption: 1,
  },
  {
    id: 337,
    question: "What is the difference between bytes and bytes32 in Solidity?",
    options: ["bytes is dynamic-length while bytes32 is fixed-length", "bytes32 is always a private key"],
    correctOption: 0,
  },
  {
    id: 338,
    question: "What is an enum in Solidity?",
    options: ["A network RPC endpoint", "A user-defined set of named choices"],
    correctOption: 1,
  },
  {
    id: 339,
    question: "What is a struct in Solidity?",
    options: ["A custom type grouping multiple fields", "A consensus mechanism"],
    correctOption: 0,
  },
  {
    id: 340,
    question: "What is an array in Solidity?",
    options: ["A digital signature algorithm", "An ordered collection of elements"],
    correctOption: 1,
  },
  {
    id: 341,
    question: "Can Solidity arrays be fixed-size or dynamic-size?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 342,
    question: "What does address(this) refer to in Solidity?",
    options: ["The transaction sender's address", "The current contract's address"],
    correctOption: 1,
  },
  {
    id: 343,
    question: "What does tx.origin represent?",
    options: ["The original EOA that began the transaction call chain", "The current contract address"],
    correctOption: 0,
  },
  {
    id: 344,
    question: "Why is tx.origin generally discouraged for authorization?",
    options: ["It always equals zero", "Intermediary contracts can make authorization unsafe"],
    correctOption: 1,
  },
  {
    id: 345,
    question: "What is msg.sender in a nested contract call?",
    options: ["The immediate caller at that call level", "Always the original EOA"],
    correctOption: 0,
  },
  {
    id: 346,
    question: "What does selfdestruct historically relate to in the EVM?",
    options: ["A method for deleting a user's wallet app", "An opcode with contract-account effects whose semantics have changed"],
    correctOption: 1,
  },
  {
    id: 347,
    question: "What does staticcall enforce?",
    options: ["The called execution cannot modify state", "The caller must transfer ETH"],
    correctOption: 0,
  },
  {
    id: 348,
    question: "What does delegatecall execute?",
    options: ["JavaScript in a browser tab", "Another contract's code in the caller's storage context"],
    correctOption: 1,
  },
  {
    id: 349,
    question: "Why can delegatecall be security-sensitive?",
    options: ["Called code can affect the caller's storage", "It reveals the Ethereum genesis block"],
    correctOption: 0,
  },
  {
    id: 350,
    question: "What is an integer overflow?",
    options: ["A wallet connecting to two networks", "A numeric result exceeding the type's representable range"],
    correctOption: 1,
  },
  {
    id: 351,
    question: "Do modern Solidity 0.8+ arithmetic operations check overflow by default?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 352,
    question: "What does unchecked allow in Solidity?",
    options: ["Calls without signatures", "Arithmetic without default overflow checks in its block"],
    correctOption: 1,
  },
  {
    id: 353,
    question: "Why should unchecked arithmetic be used carefully?",
    options: ["Overflow or underflow may occur silently", "It changes the contract address"],
    correctOption: 0,
  },
  {
    id: 354,
    question: "What is front-running in blockchain markets?",
    options: ["Running a frontend on two servers", "Acting on observed pending-order information before another transaction executes"],
    correctOption: 1,
  },
  {
    id: 355,
    question: "What does MEV stand for?",
    options: ["Maximal Extractable Value", "Minimum Ethereum Validation"],
    correctOption: 0,
  },
  {
    id: 356,
    question: "Can transaction ordering affect outcomes in DeFi?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 357,
    question: "What is a sandwich attack?",
    options: ["Trades placed around a victim's swap to exploit price movement", "A method for backing up seed phrases"],
    correctOption: 0,
  },
  {
    id: 358,
    question: "Can setting a sensible slippage limit reduce some swap execution risk?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 359,
    question: "What is price impact?",
    options: ["The trade's effect on the market or pool price", "The number of confirmations"],
    correctOption: 0,
  },
  {
    id: 360,
    question: "What is impermanent loss associated with?",
    options: ["Storing ETH in an EOA", "Providing liquidity to certain AMM pools"],
    correctOption: 1,
  },
  {
    id: 361,
    question: "Does providing liquidity guarantee a positive return?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 362,
    question: "What is collateral in DeFi lending?",
    options: ["A blockchain's chain ID", "Assets pledged to secure borrowing"],
    correctOption: 1,
  },
  {
    id: 363,
    question: "What is overcollateralized borrowing?",
    options: ["Borrowing less value than the collateral supplied", "Borrowing without any collateral"],
    correctOption: 0,
  },
  {
    id: 364,
    question: "What is liquidation in DeFi lending?",
    options: ["Deleting a wallet from a phone", "Forced collateral sale or seizure when risk thresholds are breached"],
    correctOption: 1,
  },
  {
    id: 365,
    question: "Can volatile collateral increase liquidation risk?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 366,
    question: "What is a lending protocol's utilization rate broadly related to?",
    options: ["How many NFT images exist", "How much supplied liquidity is borrowed"],
    correctOption: 1,
  },
  {
    id: 367,
    question: "What is APY intended to express?",
    options: ["Annualized yield including compounding assumptions", "A blockchain address format"],
    correctOption: 0,
  },
  {
    id: 368,
    question: "Does a displayed APY guarantee the same future return?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 369,
    question: "What is staking on Ethereum?",
    options: ["Locking ETH to participate in Proof-of-Stake validation", "Wrapping every ERC-20 token"],
    correctOption: 0,
  },
  {
    id: 370,
    question: "What is liquid staking?",
    options: ["Mining Base with a GPU", "Receiving a transferable representation related to staked assets"],
    correctOption: 1,
  },
  {
    id: 371,
    question: "Can liquid staking tokens carry smart-contract and protocol risks?",
    options: ["Yes", "No"],
    correctOption: 0,
  },
  {
    id: 372,
    question: "What is restaking broadly intended to do?",
    options: ["Convert every NFT into ETH", "Reuse crypto-economic stake to secure additional services"],
    correctOption: 1,
  },
  {
    id: 373,
    question: "Does additional yield generally imply zero additional risk?",
    options: ["No", "Yes"],
    correctOption: 0,
  },
  {
    id: 374,
    question: "What is a token vesting schedule?",
    options: ["A wallet's RPC history", "Rules controlling when allocated tokens become transferable"],
    correctOption: 1,
  },
  {
    id: 375,
    question: "What is a cliff in a vesting schedule?",
    options: ["A type of block hash", "An initial period before scheduled tokens begin unlocking"],
    correctOption: 1,
  },
  {
    id: 376,
    question: "What is token minting?",
    options: ["Deleting transaction history", "Creating new token units according to contract rules"],
    correctOption: 1,
  },
  {
    id: 377,
    question: "What is token burning?",
    options: ["Changing an EOA into a validator", "Removing token units from circulation according to contract rules"],
    correctOption: 1,
  },
  {
    id: 378,
    question: "Does transferring tokens normally change total token supply?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 379,
    question: "Can minting increase total supply if the token contract permits it?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 380,
    question: "Can burning reduce total supply if implemented that way?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 381,
    question: "What is an NFT token URI commonly used for?",
    options: ["Selecting Ethereum validators", "Pointing to token metadata"],
    correctOption: 1,
  },
  {
    id: 382,
    question: "Can NFT metadata be stored fully onchain?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 383,
    question: "Can NFT metadata also reference offchain or decentralized storage?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 384,
    question: "What is IPFS?",
    options: ["An Ethereum consensus client", "A content-addressed peer-to-peer data network"],
    correctOption: 1,
  },
  {
    id: 385,
    question: "What does content addressing identify data by?",
    options: ["The owner's wallet balance", "A hash derived from its content"],
    correctOption: 1,
  },
  {
    id: 386,
    question: "If content changes, should its content-addressed identifier normally change?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 387,
    question: "What is ENS primarily used for?",
    options: ["Compressing rollup batches", "Human-readable names linked to Ethereum-related resources"],
    correctOption: 1,
  },
  {
    id: 388,
    question: "Can an ENS name resolve to an Ethereum address?",
    options: ["No", "Yes"],
    correctOption: 1,
  },
  {
    id: 389,
    question: "Does owning an ENS name reveal the owner's private key?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 390,
    question: "What is SIWE?",
    options: ["Secure Indexing With EVM", "Sign-In with Ethereum"],
    correctOption: 1,
  },
  {
    id: 391,
    question: "What does Sign-In with Ethereum use to authenticate?",
    options: ["A user's public seed phrase", "A signed message from an Ethereum account"],
    correctOption: 1,
  },
  {
    id: 392,
    question: "Does SIWE require sending an onchain transaction for every login?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 393,
    question: "Why should a SIWE message include a nonce?",
    options: ["To increase token supply", "To help prevent replay attacks"],
    correctOption: 1,
  },
  {
    id: 394,
    question: "Why should authentication signatures be domain-bound?",
    options: ["To change the user's chain ID", "To reduce reuse on unintended sites"],
    correctOption: 1,
  },
  {
    id: 395,
    question: "What is a session key in a smart-account context?",
    options: ["The Ethereum genesis private key", "A limited key authorized for specific actions or duration"],
    correctOption: 1,
  },
  {
    id: 396,
    question: "Why can session keys improve dapp usability?",
    options: ["They make all contracts immutable", "They can reduce repeated primary-wallet prompts under defined limits"],
    correctOption: 1,
  },
  {
    id: 397,
    question: "Should session keys have broader permissions than necessary?",
    options: ["Yes", "No"],
    correctOption: 1,
  },
  {
    id: 398,
    question: "What is least-privilege authorization?",
    options: ["Giving every key unlimited access", "Granting only the permissions needed"],
    correctOption: 1,
  },
  {
    id: 399,
    question: "Why is least privilege useful in smart accounts?",
    options: ["It guarantees no software bugs", "It limits damage if a delegated credential is compromised"],
    correctOption: 1,
  },
  {
    id: 400,
    question: "What is transaction simulation used for?",
    options: ["Changing a finalized block", "Previewing likely execution results before submission"],
    correctOption: 1,
  },
];

export function getUtcDay(): number {
  return Math.floor(Date.now() / 86_400_000);
}

const QUESTION_BANK_V2_START_DAY = 20719;
const LEGACY_QUESTION_COUNT = 10;

export function getQuestionForDay(day: number): DailyQuestion {
  if (day < QUESTION_BANK_V2_START_DAY) {
    return questions[day % LEGACY_QUESTION_COUNT];
  }

  const index =
    (LEGACY_QUESTION_COUNT + (day - QUESTION_BANK_V2_START_DAY)) %
    questions.length;

  return questions[index];
}
